version: 2
jobs:
  safety:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build image
          command: "docker build -t panda_safety -f tests/safety/Dockerfile ."
      - run:
          name: Run safety test
          command: |
            docker run panda_safety /bin/bash -c "cd /panda/tests/safety; ./test.sh"

  misra-c2012:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build image
          command: "docker build -t panda_misra -f tests/misra/Dockerfile ."
      - run:
          name: Run Misra C 2012 test
          command: |
            mkdir /tmp/misra
            docker run -v /tmp/misra:/tmp/misra panda_misra /bin/bash -c "cd /panda/tests/misra; ./test_misra.sh"
      - store_artifacts:
          name: Store misra test output
          path: /tmp/misra/output.txt

  strict-compiler:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build image
          command: "docker build -t panda_strict_compiler -f tests/build_strict/Dockerfile ."
      - run:
          name: Build Panda with strict compiler rules
          command: |
            docker run panda_strict_compiler /bin/bash -c "cd /panda/board; make -f Makefile.strict clean; make -f Makefile.strict bin"

  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build image
          command: "docker build -t panda_build -f tests/build/Dockerfile ."
      - run:
          name: Test python package installer
          command: |
            docker run panda_build /bin/bash -c "cd /panda; python setup.py install"
      - run:
          name: Build Panda STM image
          command: |
            docker run panda_build /bin/bash -c "cd /panda/board; make bin"
      - run:
          name: Build Panda STM bootstub image
          command: |
            docker run panda_build /bin/bash -c "cd /panda/board; make obj/bootstub.panda.bin"
      - run:
          name: Build Pedal STM image
          command: |
            docker run panda_build /bin/bash -c "cd /panda/board/pedal; make obj/comma.bin"
      - run:
          name: Build Pedal STM bootstub image
          command: |
            docker run panda_build /bin/bash -c "cd /panda/board/pedal; make obj/bootstub.bin"
      - run:
          name: Build ESP image
          command: |
            docker run panda_build /bin/bash -c "cd /panda/boardesp; make user1.bin"

workflows:
  version: 2
  main:
    jobs:
      - safety
      - misra-c2012
      - strict-compiler
      - build
